import type { Metadata } from "next";
import { MonteCarlo,Open_Sans,Inter } from "next/font/google";
import "./globals.css";
import { MainNavbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

const monteCarlo = MonteCarlo({
  variable: "--font-monte",
  subsets: ["latin"],
  weight:["400"]
});
const openSans  = Inter ({
  variable: "--font-openSans ",
  subsets: ["latin"],
  weight:["400","300","500","600","700","800"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${monteCarlo.variable} ${openSans.variable} antialiased`}>
        <MainNavbar />
        <div className="pt- bg-white">{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
