import type { Metadata } from "next";
import { MonteCarlo, League_Spartan } from "next/font/google";
import "./globals.css";
import { MainNavbar } from "@/components/Navbar";

const monteCarlo = MonteCarlo({
  variable: "--font-monte",
  subsets: ["latin"],
  weight:["400"]
});

const spartan = League_Spartan({
  variable: "--font-spartan",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${monteCarlo.variable} ${spartan.variable} antialiased`}>
        <MainNavbar />
        <div className="pt- bg-white">{children}</div>
      </body>
    </html>
  );
}
